services:

  #React Nextjs Node Service

  node:

    image: webskittersdocker/node20:latest

    container_name: casacall-ui-node20

    restart: unless-stopped

    working_dir: /home/wtsadmin/myapp

    environment:

      - NODE_ENV=production


    volumes:

      - ./:/home/wtsadmin/myapp

    ports:

      - "14059:14059"
    command: >
      sh -c "npm run build &&
             npm start"


#Docker Networks

networks:
  default:
    external:
      name: webskitters



